# Generated by Django 5.0.3 on 2024-03-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendEaseApp', '0002_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
