# Generated by Django 5.0.3 on 2024-03-20 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendEaseApp', '0003_customuser_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
